name: Metrics
permissions:
  contents: write
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          # General config
          template: classic
          config_timezone: Asia/Karachi
          base: ""
          config_order: isocalendar, languages, calendar, stars, followup, habits, achievements

          # ISO calendar (weekly commits heatmap)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css

          # Contributions calendar
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # Stargazer evolution
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: chart

          # Issues & PRs follow-up
          plugin_followup: yes

          # Coding habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 6
