name: Generate GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kinzaAmin
          base: header, activity, community, repositories, metadata
          template: classic
          config_timezone: Asia/Karachi
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_contributors: yes
          plugin_calendar: yes
          plugin_lines: yes
          plugin_followup: yes
          plugin_repositories: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_limit: 5

